### ISSUE TITLE
SHC Module

### ISSUE THREAD

**Issue by N0ot-No0t** [m-triassi/smart-home-simulator-team12#29]
## Description
Parent Issue: #XX
_What will this feature do?_
Enable user to interact with the Smart home core functionality (SHC) module

## Tasks (Optional)
_What needs to get done for this feature?_
- [ ] System shall allow users /smart home modules to open/close doors
- [ ] System shall allow users /smart home modules to open/close windows
- [ ] System shall allow users /smart home modules to turn on/off lights
- [ ] System shall allow users to set an Auto mode, that turn on/off lights automatically when someone enters to a room
