### ISSUE TITLE
SHP Module (possible duplicate)

### ISSUE THREAD

**Issue by N0ot-No0t** [m-triassi/smart-home-simulator-team12#30]
## Description
Parent Issue: #XX
_What will this feature do?_
Enable the user to interact with the Smart home security (SHP) Module.

## Tasks (Optional)
_What needs to get done for this feature?_
- [ ] System shall allow users to set an _away mode_
- [ ] System shall send notification to users  if any motion detectors are triggered while the user is away
- [ ] System shall allow users  to set how much time should pass before alerting the authorities, when motion detectors are triggered during set away mode
